// npm run build  (Vercel runs this on every deploy)
// 1. Publishes docs/privacy-policy.md as public/privacy.html, with only the optional clauses switched on in docs/privacy-features.json.
// 2. Copies fonts and the Supabase sign-in library into public/, so no page loads anything from a third party.
// A production deploy fails while the policy still has [●] placeholders, unless ALLOW_DRAFT_POLICY=1.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';
import { PRIVACY_NOTICE_VERSION } from '../lib/privacy.js';
import { renderPolicySource } from './policy-source.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const at = (...p) => path.join(root, ...p);

// ---------- Privacy policy ----------
const features = JSON.parse(fs.readFileSync(at('docs/privacy-features.json'), 'utf8'));
const md = fs.readFileSync(at('docs/privacy-policy.md'), 'utf8');
const version = /\*\*Version:\*\*\s*([\d.]+)/.exec(md)?.[1];
if (version !== PRIVACY_NOTICE_VERSION) {
  console.error(`Policy version ${version} does not match PRIVACY_NOTICE_VERSION ${PRIVACY_NOTICE_VERSION} in lib/privacy.js.`);
  process.exit(1);
}
const source = renderPolicySource(md, features);
if (/▣/.test(source)) { console.error('An optional clause marker was not resolved.'); process.exit(1); }

const placeholders = source.match(/\[●[^\]]*\]/g) || [];
const production = process.env.VERCEL_ENV === 'production';
if (placeholders.length && production && process.env.ALLOW_DRAFT_POLICY !== '1') {
  console.error(`The privacy policy still has ${placeholders.length} [●] placeholders. Fill them in docs/privacy-policy.md before deploying to production.`);
  process.exit(1);
}

const renderer = new marked.Renderer();
renderer.heading = (text, level) => {
  const id = text.replace(/<[^>]+>/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `<h${level} id="${id}">${text}</h${level}>\n`;
};
let body = marked.parse(source, { renderer, gfm: true });
body = body.replace(/\[●([^\]]*)\]/g, (_, t) => `<mark class="todo">[to complete${t.trim() ? ': ' + t.trim() : ''}]</mark>`);
body = body.replace(/<table>/g, '<div class="tablewrap"><table>').replace(/<\/table>/g, '</table></div>');

const draft = placeholders.length
  ? `<p class="draftbar">Draft: ${placeholders.length} details still to be completed before this policy is published.</p>` : '';

fs.writeFileSync(at('public/privacy.html'), `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Woezor Rides Privacy Policy</title>
<meta name="description" content="How Astrovenza Ventures collects, uses and protects personal data on Woezor Rides airport pickups.">
<link rel="stylesheet" href="/fonts.css">
<link rel="stylesheet" href="/styles.css">
</head>
<body>
<div class="app">
  <header class="top">
    <div class="mark" aria-hidden="true"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M21 16v-2l-8-5V3.5a1.5 1.5 0 0 0-3 0V9l-8 5v2l8-2.5V19l-2 1.5V22l3.5-1 3.5 1v-1.5L13 19v-5.5l8 2.5z"/></svg></div>
    <div><h1>Woezor</h1><p><a href="/">Book a pickup</a> · <a href="/driver">Driver app</a></p></div>
  </header>
  ${draft}
  <article class="panel policy">
${body}
  </article>
  <footer>Woezor Rides is a digital product of Astrovenza Ventures, Ghana. Contact: astrovenzav@gmail.com · <a href="/privacy">Privacy policy</a></footer>
</div>
</body>
</html>
`);
console.log(`privacy.html: version ${version}, features on: ${Object.keys(features).filter((k) => k !== '_help' && features[k]).join(', ') || 'none'}, ${placeholders.length} placeholders left`);

// ---------- Self-hosted fonts and sign-in library ----------
fs.mkdirSync(at('public/fonts'), { recursive: true });
fs.mkdirSync(at('public/vendor'), { recursive: true });
const fonts = [
  ['Barlow Condensed', 'barlow-condensed', [600, 700]],
  ['IBM Plex Sans', 'ibm-plex-sans', [400, 500, 600]],
  ['IBM Plex Mono', 'ibm-plex-mono', [500, 600]]
];
let css = '/* Generated by scripts/build.mjs from @fontsource packages (SIL Open Font License). */\n';
for (const [family, pkg, weights] of fonts) {
  for (const w of weights) {
    const file = `${pkg}-latin-${w}-normal.woff2`;
    fs.copyFileSync(at('node_modules/@fontsource', pkg, 'files', file), at('public/fonts', file));
    css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${w};font-display:swap;src:url(/fonts/${file}) format('woff2');}\n`;
  }
}
fs.writeFileSync(at('public/fonts.css'), css);
fs.copyFileSync(at('node_modules/@supabase/supabase-js/dist/umd/supabase.js'), at('public/vendor/supabase.js'));
console.log('fonts and vendor/supabase.js copied');
